//uploading city
POST http://localhost:5001/cityname 
Content-Type: application/json

 {
    "name": "Mysore",
    "population": 1494000,
    "country": "India",
    "latitude": 67.3618,
    "longitude": 49.4747
}


// getting city based on the querries
### 
GET http://localhost:5001/cityname


### 
GET http://localhost:5001/cityname?filter={"country":"India"}&page=1&limit=10

### 
GET http://localhost:5001/cityname?projection=name,population,country&search=Delhi

### 

DELETE http://localhost:5001/cityname/Bidar



// update city
### 
PUT http://localhost:5001/cityname/Delhi
Content-Type: application/json

 {
    "population"  :1055000, 
    "country" : "India", 
    "latitude" : 175.687, 
    "longitude" : 789.23

 }